blank_issues_enabled: false
contact_links:
    - name: Q & A
      url: https://github.com/eamodio/vscode-find-related/discussions?discussions_q=category%3AQ%26A
      about: Ask and answer questions about Find Related Files
    - name: Documentation
      url: https://github.com/eamodio/vscode-find-related/#readme
      about: Read the Find Related Files support documentation
